# The cleanup step is executed directly before every destroy step. Just like the destroy step, it will be run twice. An initial clean before converge and then a clean before the last destroy step. This means that the cleanup playbook must handle failures to cleanup resources which have not been created yet.
---
# TODO: figure out how to set the user_name so that it can be shared between playbooks.  hardcoding for now.
- name: cleanup
  hosts: all
  roles:
    - role: ansible-modules-bitwarden
  vars:
    git_token: "{{lookup('bitwarden', 'ansible-github')}}"
  
  tasks:
    - name: Read SSH public key to authorize
      shell: cat $HOME/.ssh/id_rsa.pub
      register: ssh_pub_key
      become_user: mike
      become: true
      
    - name: username/host
      shell: echo ${USER}@$(hostname)
      register: keyname
      become_user: mike
      become: true
    
    - name: remove test ssh key
      github_deploy_key:
        owner: "mspiegel31"
        repo: "dotfiles"
        name: "{{keyname.stdout}}"
        key: "{{ssh_pub_key.stdout}}"
        token: "{{git_token}}"
        state: absent

    