---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: ubuntu:18.04
    priveliged: True
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
