---
# reference https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout
- hosts: devboxes
  become: yes
  user: root
  roles:
    - ansible-modules-bitwarden #TODO: specify as dependency, specify in requirements.yml
    - role: base
      create_user: "{{user}}"
    
    - role: github-accessible
      username: "{{ user }}"
    
    - role: zsh-configs
      username: "{{ user }}"
  vars:
    user: mike