---
# reference https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout
- hosts: devboxes
  become: yes
  become_user: root
  roles:
    - role: base
      tags: base
      create_user: "{{user}}"
    
    - role: github-accessible
      username: "{{ user }}"
    
    - role: zsh-configs
      username: "{{ user }}"
  
  post_tasks:
      #TODO:  check os here
    - name: upgrade system
      apt: upgrade=full
    
    - name: reboot server
      reboot:

  vars:
    user: mike