---
- name: Converge
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: install python if needed
      raw: test -e /usr/bin/python || (pacman -Sy --noconfirm && pacman -S python --noconfirm)
    - setup:
  roles:
    - role: base
      create_user: mike