---
# tasks file for github-accessible

- name: install openssh
  package: name=openssh-client state=present

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    state: present
  
- name: check for rsa keypair
  stat:
    path: $HOME/.ssh/id_rsa.pub
  register: public_ssh_key
  become: yes
  become_user: "{{username}}"

- name: register ssh key with github
  block:
    - name: Read SSH public key to authorize
      shell: cat $HOME/.ssh/id_rsa.pub
      register: ssh_pub_key

    - name: username/host
      become_user: "{{username}}"
      shell: echo ${USER}@$(hostname)
      register: keyname
  become_user: "{{username}}"
  become: true

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: "{{ keyname.stdout }}"
    pubkey: "{{ ssh_pub_key.stdout }}"
    token: "{{ git_token }}"
  vars:
    git_token: "{{lookup('bitwarden', 'ansible-github')}}"
  become: no
  become_method: sudo