---
- name: install vscode
  become: true
  command: snap install vscode --classic
- name: install intellij-ce
  become: true
  command: snap install intellij-idea-community --classic
- name: install guake
  become: true
  apt:
    name: guake

- name: install conky
  become: true
  apt:
    name: conky-all