---
# TODO: server should get deploy key
- name: setup oh-my-zsh
  block:
    - name: add github to known_hosts
      shell: ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

    - name: clone dotfiles repo
      git:
        repo: git@github.com:mspiegel31/dotfiles.git
        dest: $HOME/dotfiles

    - name: download install script
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: $HOME/install.sh
        mode: "a+x"

    - name: install oh-my-zsh
      shell: "$HOME/install.sh --unattended"
      args:
          creates: $HOME/.oh-my-zsh
    
    - name: remove install script
      file: path=$HOME/install.sh state=absent

    - name: remove default .zshrc
      file: path=$HOME/.zshrc state=absent

    - name: use preferred zsh configuration
      shell: stow zsh
      args:
        chdir: $HOME/dotfiles
  tags: oh-my-zsh